// HARD PUZZLES + HINTS + CHECKMARK TAGS
const puzzles = [
  {
    id: 1,
    title: "System Boot Cipher",
    text: "A corrupted boot log shows: 5, 8, 13, 21, 34, ?. Enter the missing number.",
    answer: "55",
    hint: "It’s a famous sequence where each number is the sum of the previous two.",
    tag: false,
  },
  {
    id: 2,
    title: "Encrypted Directive",
    text: "Decode the directive: 12-5-22-5-12 (A=1). Enter the resulting word.",
    answer: "level",
    hint: "Convert numbers to letters.",
    tag: true,
  },
  {
    id: 3,
    title: "Neural Pattern Sync",
    text: "The system displays: A1, C3, F6, J10, O15, ?. Enter the next alphanumeric pair.",
    answer: "U21",
    hint: "Letters jump by increasing intervals. Numbers follow a pattern too.",
    tag: false,
  },
  {
    id: 4,
    title: "Temporal Drift Test",
    text: "A timestamp loop repeats every 90 minutes. If the loop starts at 14:30, what time is the 4th loop?",
    answer: "20:00",
    hint: "Add 90 minutes three times.",
    tag: false,
  },
  {
    id: 5,
    title: "Milestone Riddle",
    text: "I mark a turning point, a decade times three. A celebrated number—what could I be?",
    answer: "30",
    hint: "Think in decades, not single years.",
    tag: true,
  },
  {
    id: 6,
    title: "Anomaly Detection",
    text: "In a security audit, the system flags one term as inconsistent with the others: ENCRYPT, SECURE, OBFUSCATE, EXPOSE. Which term does NOT belong?",
    answer: "expose",
    hint: "Three actions protect information. One does the opposite.",
    tag: false,
  },
  {
    id: 7,
    title: "Glitch Fragment",
    text: "2, 6, 12, 20, 30, ?. Enter the next number.",
    answer: "42",
    hint: "Differences increase by 2 each time.",
    tag: false,
  },
  {
    id: 8,
    title: "Memory Reconstruction",
    text: "
